version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "20:00"
  open-pull-requests-limit: 99
  commit-message: { prefix: "" }
  reviewers: [ rye ]
  assignees: [ rye ]
  allow:
  - dependency-type: all
