---
language: rust
sudo: required
cache: cargo

addons:
  apt:
    packages: [libssl-dev]

rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
  - rust: nightly

before_script:
- cargo clean
- rustup component add clippy
- rustup component add rustfmt

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --help || cargo install cargo-tarpaulin -f
  fi

script:
- if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then cargo check --all-targets && cargo clean; else cargo check && cargo clean; fi
- cargo fmt -- --check
- cargo clippy -- -D clippy::all -D clippy::cargo -W clippy::pedantic
- cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
