[package]
name = "eb"
description = "A command executor exercising exponential backoff"
edition = "2018"
version = "0.2.1"
authors = ["Kristofer Rye <kristofer.rye@gmail.com>"]
license = "GPL-3.0-only"

repository = "https://github.com/rye/eb"
readme = "README.md"
keywords = ["cli", "exponential", "backoff", "tool"]
categories = ["command-line-utilities"]

[dependencies]
clap = "2.33.0"
rand = "0.7.2"
